### ISSUE TITLE
Auth Routes not working

### ISSUE THREAD

**Issue by RajisteB** [Cityslick/Occurio#12]
It seems as if our React is not interconnected with our Express app.
When we test http://localhost:3001/auth in Postman with a Json of user info, the route works.
However, when we test http://localhost:3000/auth in Postman we get an error

Our App.js routing info seems to be correct but we cannot find the issue.

**Comment by nasser** [comment]
Why are you trying to connect to port 3000? Your express logic will only serve on port 3001 https://github.com/Cityslick/Occurio/blob/cecbc4d0930826fd984afa3380a0c730f4c4598b/app.js#L28

The code in your App.js seems fine, too.
