### ISSUE TITLE
CSS Navbar whitespace?

### ISSUE THREAD

**Issue by RajisteB** [Cityslick/Occurio#61]
Currently working on the UserProfile component...
Added a css file specifically for the component called User.css
Navigation bar css is rendered in App.css (imported into App.js) as :

```
/* HEADER */
.nav {
  display: flex;
  float: right;
  width: 100%;
  font-weight:900;
}

.nav2 {
  margin-right: 20px;
} 

.nav-list {
  width: 100%;
}

.nav-item,  {
  width: 3vw;
  padding: 20px;
  color: white
}
.nav-item a {
  display:block;
  color:#FFF;
}
.nav-item a:hover {
  background: white;
  color: #6D1CDF;
  transition: .3s;
}
.header {
  position: fixed;
  margin: 0 auto;
  display: flex;
  background-color: #6D1CDF;
  width: 100%;
  color: white;
}
```

In the header I added "margin: 0 auto;" in order to bring the fixed navbar all the way to the top of the page with no whitespace above it. However, when I log in and go to the user profile page, the navbar reverts and there is a line of whitespace above it. 

Also, due to it being fixed, the text rendered in the component slides behind the navigation bar as well...

I figured that since I changed it in App.css the same properties would carry over to the individual components but that is not the case.
Thoughts?

**Comment by jlr7245** [comment]
Well, the text sliding down the navigation bar is something you'll have to fix by giving the text a top margin of some kind. Also, you might try giving the header a `top: 0` property.
